title: Amy Tibbetts # y-newour name (or website title) here
logo: "/images/logo_new.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mechanical Engineer turned Data Analyst/Engineer/Scientist with 8+ years of experience in Advanced Driver Assistance Systems, self-driving vehicles, and transportation. 2+ years of experience harnessing data to drive strategic decisions in transportation and urban planning. My expertise includes translating complex metrics into actionable insights and empowering clients to make informed decisions. My passion is crafting strategies that shape equitable, safe, and forward-thinking urban landscapes as well as informing policy and improving processes. 
  <br><br>
  <b>Top Skills:</b>
  <br>Python
  <br>R
  <br>ArcGIS Pro
  <br>SQL
  <br>Power BI
  <br>Tableau  
  <br><br>
  <a href="https://www.linkedin.com/in/amy-tibbetts-a276452b/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://atibbetts.github.io/atibbetts/data_viz">Data Visualizations</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
